# Generated by Django 2.2.14 on 2020-09-08 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Length has to be 4', regex='^.{8}$')])),
            ],
        ),
    ]
