# Generated by Django 2.2.14 on 2020-09-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200921_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_long',
            field=models.BooleanField(default=False),
        ),
    ]
